### ISSUE TITLE
Tests Pass with Panic

### ISSUE THREAD

**Issue by tynes** [foundry-rs/hardhat#39]
See https://github.com/foundry-rs/hardhat/runs/6646586678?check_suite_focus=true

```
@foundry-rs/hardhat
 | thread 'main' panicked at 'error binding to 127.0.0.1:8545: error creating server listener: Address already in use (os error 98)', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.18/src/server/server.rs:87:17
 | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
@foundry-rs/hardhat-anvil
 |     ✔ can send transaction (386ms)
 |     ✔ can send transaction with env provider
 | 
```

It looks like `anvil` has already started and its trying to be started again?

**Comment by mattsse** [comment]
there's likely a race condition where tests that launch anvil run at the same, not familiar with how tests are scheduled in js. but perhaps the easiest way to mitigate this would be to use the --port option in the tests that launch an instance?
